MODEL:
  BACKBONE:
    LAST_STAGE_BLOCK: 4
    DILATION: true
    OUTPUT_LAYERS:
    - stage3  # ori layer3
    TYPE: resnet50  # ori resnet50
  HIDDEN_DIM: 128
  HEAD_DIM: 128  # ori 256
  TRANSFORMER:
    DIM_FEEDFORWARD: 2048
    DROPOUT: 0.1
    NHEADS: 8
  HEAD:
    CONVNET:
      INPUT_DIM: 400
      HIDDEN_DIM: 200
      OUTPUT_DIM: 100
      PADDING: 1
      KERNEL: 3
    LINEARNET:
      INPUT_DIM: 3200
      HIDDEN_DIM: 320
      NEXT_DIM: 32
DATA:
  PATH: /home/tigran/scripts
  MEAN:
  - 0.485
  - 0.456
  - 0.406
  SEARCH:
    CENTER_JITTER: 4.5  # ori 4.5
    FACTOR: 5.0  #  ori 5.0
    SCALE_JITTER: 0.5  # ori 0.5
    SIZE: 320  # ori 320
    FEAT_SIZE: 20
  STD:
  - 0.229
  - 0.224
  - 0.225
  TEMPLATE:
    CENTER_JITTER: 0
    FACTOR: 2.0
    SCALE_JITTER: 0
    SIZE: 128
    FEAT_SIZE: 20
  TRAIN:
    DATASETS_NAME:
    - LASOT
    - GOT10K_vottrain
    - COCO17
    - TRACKINGNET
    DATASETS_RATIO:
    - 1
    - 1
    - 1
    - 1
    SAMPLE_PER_EPOCH: 10000
  VAL:
    PATH: /home/tigran/scripts/test
    LIST: 
    - data
    PAIRS_LIST: 
    - pairs.txt
    MEAN:
    - 0.485
    - 0.456
    - 0.406
TRAIN:
  AMP: False
  BACKBONE_MULTIPLIER: 0.1
  BATCH_SIZE: 64
  DEEP_SUPERVISION: false
  EPOCH: 100
  FREEZE_BACKBONE_BN: true
  BACKBONE_TRAINED_LAYERS:
  - stage1
  - stage2
  - stage3
  GIOU_WEIGHT: 2.0
  GRAD_CLIP_NORM: 0.1
  L1_WEIGHT: 5.0
  LR: 0.0001
  LR_DROP_EPOCH: 400
  NUM_WORKER: 8
  OPTIMIZER: ADAMW
  PRINT_INTERVAL: 50
  SCHEDULER:
    TYPE: step
    DECAY_RATE: 0.1
  VAL_EPOCH_INTERVAL: 20
  WEIGHT_DECAY: 0.0001
  
